name: Node CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Print port
        run: echo "${{ env.PORT }}"
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - run: npm install
      - run: npm run build --if-present
      - run: npm run start

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          token: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          # clean: true

